syntax = "proto3";

option csharp_namespace = "ChatApp.gRPC";

package chat;

service ChatService {
  rpc SendMessage (SendMessageRequest) returns (SendMessageResponse);
  rpc GetMessages (GetMessagesRequest) returns (GetMessagesResponse);
}

message SendMessageRequest {
  string inbox_id = 1;
  string sender_id = 2;
  string content = 3;
}

message SendMessageResponse {
  bool success = 1;
}

message GetMessagesRequest {
  string inbox_id = 1;
}

message GetMessagesResponse {
  repeated Message messages = 1;
}

message Message {
  string sender_id = 1;
  string content = 2;
  string sent_at = 3;
}
